authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('logout/', authapp.logout, name='logout'),
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit')
]

geekshop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from .views import index, contacts

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),

    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin_stuff/', include('adminapp.urls', namespace='admin_stuff')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basketapp/models.py
from django.conf import settings
from django.db import models

from mainapp.models import Product


class Basket(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='basket',
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE
    )
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)
    add_datetime = models.DateTimeField(verbose_name='время', auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} - {self.product.name} - {self.quantity} - {self.add_datetime}'

    @property
    def product_cost(self):
        return self.product.price * self.quantity

    @property
    def total_quantity(self):
        _items = Basket.objects.filter(user=self.user)
        _totalquantity = sum(list(map(lambda x: x.quantity, _items)))
        return _totalquantity

    @property
    def total_cost(self):
        _items = Basket.objects.filter(user=self.user)
        _totalcost = sum(list(map(lambda x: x.product_cost, _items)))
        return _totalcost

basketapp/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse

from basketapp.models import Basket
from mainapp.models import Product

from django.contrib.auth.decorators import login_required


@login_required
def basket(request):
    title = 'корзина'
    basket_items = Basket.objects.filter(user=request.user).order_by('product__category')

    context = {
        'title': title,
        'basket_items': basket_items,
    }
    return render(request, 'basketapp/list.html', context)


@login_required
def basket_add(request, pk):
    if 'login' in request.META.get('HTTP_REFERER'):
        return HttpResponseRedirect(reverse('products:detail', args=[pk]))

    product = get_object_or_404(Product, pk=pk)

    basket = Basket.objects.filter(user=request.user, product=product).first()

    if not basket:
        basket = Basket(user=request.user, product=product)

    basket.quantity += 1
    basket.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_remove(request, pk):
    basket_record = get_object_or_404(Basket, pk=pk)
    basket_record.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_edit(request, pk, quantity):
    quantity = int(quantity)
    new_basket_item = Basket.objects.get(pk=int(pk))

    if quantity > 0:
        new_basket_item.quantity = quantity
        new_basket_item.save()
    else:
        new_basket_item.delete()

    basket_items = Basket.objects.filter(user=request.user).order_by('product__category')

    context = {
        'basket_items': basket_items,
    }

    result = render_to_string('basketapp/includes/inc_basket_list.html', context)

    return JsonResponse({'result': result})

basketapp/templates/basketapp/includes/inc_basket_list.html
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Картинка</th>
                <th scope="col">Категория</th>
                <th scope="col">Имя товара</th>
                <th scope="col">Цена</th>
                <th scope="col">Количество</th>
                <th scope="col">Сумма</th>
                <th scope="col">Удалить</th>
            </tr>
            </thead>
            <tbody>
            {% for item in basket_items %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td><img src="/media/{{ item.product.image }}" alt="{{ item.product.short_desc }}"></td>
                    <td>{{ item.product.category.name }}</td>
                    <td>{{ item.product.name }}</td>
                    <td>{{ item.product.price }}&nbspруб</td>
                    <td><input type="number" name="{{ item.pk }}" min="0" value="{{ item.quantity }}"></td>
                    <td>{{ item.product_cost }}&nbspруб</td>
                    <td>
                        <button class="btn btn-round">
                            <a href="{% url 'basket:remove' item.pk %}" class="">
                                удалить
                            </a>
                        </button>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% if basket_items %}
            <div class="basket_summary">
                В корзине {{ basket_items.0.total_quantity }} товаров общей стоимостью
                {{ basket_items.0.total_cost }} руб
            </div>
        {% endif %}


    </div>